-- Baseline schema for Legacy Analyzer.
-- VARCHAR identifiers intentionally match the existing JPA model, whose UUIDs are stored as strings.

CREATE TABLE analysis_runs (
    id VARCHAR(255) PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    analyzer_version VARCHAR(100),
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE source_files (
    id VARCHAR(255) PRIMARY KEY,
    analysis_run_id VARCHAR(255) NOT NULL,
    file_path VARCHAR(2048) NOT NULL,
    content_hash VARCHAR(128),
    source_type VARCHAR(50) NOT NULL,
    parsed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source_files_analysis_run
        FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs (id) ON DELETE CASCADE,
    CONSTRAINT uk_source_files_run_path UNIQUE (analysis_run_id, file_path)
);

CREATE TABLE legacy_objects (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(255),
    source_code TEXT,
    procedures TEXT,
    referenced_tables TEXT,
    code_smells VARCHAR(255),
    risk_score INTEGER,
    risk_level VARCHAR(255),
    created_at TIMESTAMP,
    functional_summary VARCHAR(255)
);

CREATE TABLE ast_nodes (
    id VARCHAR(255) PRIMARY KEY,
    source_file_id VARCHAR(255) NOT NULL,
    legacy_object_id VARCHAR(255),
    parent_node_id VARCHAR(255),
    node_type VARCHAR(255) NOT NULL,
    node_name VARCHAR(255),
    line_start INTEGER,
    column_start INTEGER,
    line_end INTEGER,
    column_end INTEGER,
    source_fragment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ast_nodes_source_file
        FOREIGN KEY (source_file_id) REFERENCES source_files (id) ON DELETE CASCADE,
    CONSTRAINT fk_ast_nodes_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE,
    CONSTRAINT fk_ast_nodes_parent
        FOREIGN KEY (parent_node_id) REFERENCES ast_nodes (id) ON DELETE CASCADE
);

CREATE TABLE entity_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id VARCHAR(255) NOT NULL,
    source_object_id VARCHAR(255) NOT NULL,
    target_object_id VARCHAR(255) NOT NULL,
    relation_type VARCHAR(100) NOT NULL,
    source_ast_node_id VARCHAR(255),
    confidence_level DOUBLE PRECISION,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_entity_relations_analysis_run
        FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs (id) ON DELETE CASCADE,
    CONSTRAINT fk_entity_relations_source_object
        FOREIGN KEY (source_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE,
    CONSTRAINT fk_entity_relations_target_object
        FOREIGN KEY (target_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE,
    CONSTRAINT fk_entity_relations_ast_node
        FOREIGN KEY (source_ast_node_id) REFERENCES ast_nodes (id) ON DELETE SET NULL,
    CONSTRAINT uk_entity_relations_identity
        UNIQUE (analysis_run_id, source_object_id, target_object_id, relation_type, source_ast_node_id)
);

CREATE TABLE table_dependencies (
    id VARCHAR(255) PRIMARY KEY,
    source_table VARCHAR(255),
    target_table VARCHAR(255),
    object_name VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE knowledge_relation_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(255),
    relation VARCHAR(255),
    target VARCHAR(255),
    source_object VARCHAR(255),
    source_line_start INTEGER,
    source_line_end INTEGER,
    code_snippet TEXT,
    confidence_level DOUBLE PRECISION,
    analysis_id VARCHAR(255),
    CONSTRAINT uk_knowledge_relation_identity
        UNIQUE (source, relation, target, analysis_id)
);

CREATE TABLE cursor_metadata (
    id VARCHAR(255) PRIMARY KEY,
    cursor_name VARCHAR(255),
    bulk_collect BOOLEAN NOT NULL,
    for_update BOOLEAN NOT NULL,
    forall_usage BOOLEAN NOT NULL,
    legacy_object_id VARCHAR(255),
    CONSTRAINT fk_cursor_metadata_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE
);

CREATE TABLE subprogram_nodes (
    id VARCHAR(255) PRIMARY KEY,
    subprogram_name VARCHAR(255),
    qualified_name VARCHAR(255),
    subprogram_type VARCHAR(255),
    legacy_object_id VARCHAR(255),
    CONSTRAINT fk_subprogram_nodes_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE
);

CREATE TABLE business_rules (
    id VARCHAR(255) PRIMARY KEY,
    error_code VARCHAR(255),
    message TEXT,
    legacy_object_id VARCHAR(255),
    CONSTRAINT fk_business_rules_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE
);

CREATE TABLE exception_metadata (
    id VARCHAR(255) PRIMARY KEY,
    exception_name VARCHAR(255),
    generic_handler BOOLEAN NOT NULL,
    legacy_object_id VARCHAR(255),
    CONSTRAINT fk_exception_metadata_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE
);

CREATE TABLE dblink_metadata (
    id VARCHAR(255) PRIMARY KEY,
    db_link_name VARCHAR(255),
    remote_object VARCHAR(255),
    legacy_object_id VARCHAR(255),
    CONSTRAINT fk_dblink_metadata_legacy_object
        FOREIGN KEY (legacy_object_id) REFERENCES legacy_objects (id) ON DELETE CASCADE
);

CREATE INDEX idx_source_files_analysis_run ON source_files (analysis_run_id);
CREATE INDEX idx_ast_nodes_source_file ON ast_nodes (source_file_id);
CREATE INDEX idx_ast_nodes_legacy_object ON ast_nodes (legacy_object_id);
CREATE INDEX idx_ast_nodes_parent ON ast_nodes (parent_node_id);
CREATE INDEX idx_entity_relations_source ON entity_relations (source_object_id);
CREATE INDEX idx_entity_relations_target ON entity_relations (target_object_id);
CREATE INDEX idx_table_dependencies_source ON table_dependencies (source_table);
CREATE INDEX idx_table_dependencies_target ON table_dependencies (target_table);
CREATE INDEX idx_table_dependencies_object ON table_dependencies (object_name);
CREATE INDEX idx_knowledge_relations_source ON knowledge_relation_entity (source);
CREATE INDEX idx_knowledge_relations_target ON knowledge_relation_entity (target);
CREATE INDEX idx_knowledge_relations_analysis ON knowledge_relation_entity (analysis_id);
CREATE INDEX idx_cursor_metadata_object ON cursor_metadata (legacy_object_id);
CREATE INDEX idx_subprogram_nodes_object ON subprogram_nodes (legacy_object_id);
CREATE INDEX idx_business_rules_object ON business_rules (legacy_object_id);
CREATE INDEX idx_exception_metadata_object ON exception_metadata (legacy_object_id);
CREATE INDEX idx_dblink_metadata_object ON dblink_metadata (legacy_object_id);
